### ISSUE TITLE
插件无法正常使用

### ISSUE THREAD

**Issue by AkarinLiu** [zmoyi/WalineJson#3]
Typecho 版本： 1.3.0
描述： 安装该插件后，无法正常启用。
错误码： 500

**Comment by zmoyi** [comment]
过段时间修复一下

**Comment by AkarinLiu** [comment]
不好意思，我找错Repo了，是这个：https://github.com/lizheming/typecho-export-valine

**Comment by zmoyi** [comment]
ok
